name: Maven Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - run: |
          download_url="https://download.java.net/java/GA/jdk19.0.1/afdd2e245b014143b62ccb916125e3ce/10/GPL/openjdk-19.0.1_linux-x64_bin.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - name: Set up JDK 19.0.1
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '19.0.1'
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -B -Drevision=${GITHUB_SHA::7}

  release:
    needs: build
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - run: |
          download_url="https://download.java.net/java/GA/jdk19.0.1/afdd2e245b014143b62ccb916125e3ce/10/GPL/openjdk-19.0.1_linux-x64_bin.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - name: Set up JDK 19.0.1
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '19.0.1'
          architecture: x64

      - name: Build with Maven
        run: mvn clean install -B

      - name: Create Tag
        run: |
          export SHORT_SHA=$(git rev-parse --short HEAD)
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag "$SHORT_SHA"
          git push origin tag "$SHORT_SHA"
          echo "tag_name=$SHORT_SHA" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: ./target/*.jar
          tag_name: ${{env.SHORT_SHA}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
